# Generated by Django 5.0.3 on 2024-03-07 07:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_remove_product_category_product_product_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[("EL", "Electronics"), ("CL", "Clothing"), ("FD", "Food")],
                max_length=255,
            ),
        ),
    ]
